### ISSUE TITLE
issues with reading .config/kion/config.yml

### ISSUE THREAD

**Issue by CodaBool** [corbaltcode/kion#15]
I am trying to authenticate with the scout accounts. I am able to use the CLI for all the other scout accounts `dev`, `prod`, `impl` but I run into a 400 error with `test`. What's strange is that the credentials command when supplied the values for account id and role name 

> working command

```
kion credentials --account-id 001265600887 --cloud-access-role scout-application-admin
```

but when I try to have kion read from the .config/kion/config.yml by just giving it the command 

> not working

```
kion credentials
```

I get this error message

`kion: account not found (400)`

and to show what values it's reading. Here is the contents of my .config/kion/config.yml

``` 
app-api-key-duration: 168h0m0s
host: cloudtamer.cms.gov
idms: 2
region: us-east-1
rotate-app-api-keys: false
session-duration: 1h0m0s
username: MYYG
account-id: 001265600887
cloud-access-role: scout-application-admin
```

The same method works for all other scout account environments. Is there some store of accounts that needs updated?

**Comment by CodaBool** [comment]
> Nope
![image](https://github.com/corbaltcode/kion/assets/61724833/27f5a06d-3cc2-44ef-8a16-09988c0be448)

**Comment by leslie-corbalt** [comment]
The file ~/.config/kion/config.yml should not contain `account-id`. Did you manually add it? In the README:
Read `Setup` again. There is no account-id.
Then read `Config and kion.yml`
Then read `AWS CLI Credential Process`.
You can set you account-id on the command line, kion.yml, and in a profile.

**Comment by jonahb** [comment]
@CodaBool As Leslie said, you shouldn't put `account-id` in the global config file. Instead, specify it on the command line or in a local `kion.yml`.

What you've done would probably work, however, if you put double quotes around the account ID: `account-id: "001265600887"`. Otherwise, it's interpreted as a number, and the leading zeroes are lost.

**Comment by CodaBool** [comment]
Ok good to know about the string double quotes I can see if that fixes something. I have a wrapper cli around yours that I've been using. 

Wds Ops has 24 V4 accounts to manage and it seems writing to the shared global config was the easiest (although hacky) way to auth.

https://github.com/oddballteam/fast-auth

**Comment by jonahb** [comment]
@CodaBool We also manage a bunch of accounts. The way we handle this is to create a directory for each account (a Terraform workspace) and put a [kion.yml](https://github.com/corbaltcode/kion#config-and-kionyml) in each directory. When we do `kion credentials` or `kion console` in one of these directories, the Kion Tool automatically picks up the right account ID and Cloud Access Role.

Also, I noticed that your code has a message about logging out of the AWS console. In the latest version of the Kion Tool, you can do `kion console --logout` to end the current session before opening a new console.

**Comment by CodaBool** [comment]
The double quotes solves my main issue. :smile: 

The `console --logout` seems to have issues for me.

I'm on Ubuntu with deb installed firefox. The default Ubuntu is installed with snap firefox which is probably even more restrictive about its file mounting.
- firefox doesn't have access to all files on /tmp
- After moving the html to a folder it could access I get a CSP block on inline `script-src`

But I can create a separate issue for that if you're interested.
